### ISSUE TITLE
docker_container and docker_image fail in OpsWorks running Chef 11.10

### ISSUE THREAD

**Issue by michaelshobbs** [bflad/chef-docker#183]
I'm attempting to use the LWRPs in this cookbook and am running into issues in Chef 11.10 (Ruby 2.0.0) environments in AWS OpsWorks. For the record, this recipe works fine in Chef 11.4 (Ruby 1.8.7).  Both docker_image and docker_container fail in similar ways. Any help would be great! Thanks.

Recipe:
```
docker_image "jpetazzo/nsenter"

docker_container "jpetazzo/nsenter" do
    volume "/usr/local/bin:/target"
end
```

docker_image error:
```
================================================================================
Error executing action `pull` on resource 'docker_image[jpetazzo/nsenter]'
================================================================================


TypeError
---------
no implicit conversion of nil into String


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/image.rb:160:in `start_with?'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/image.rb:160:in `image_id_matches?'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/image.rb:10:in `block in load_current_resource'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/image.rb:8:in `each_line'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/image.rb:8:in `load_current_resource'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache/cookbooks/app/recipes/nsenter.rb

  1: docker_image "jpetazzo/nsenter"
  2:



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache/cookbooks/app/recipes/nsenter.rb:1:in `from_file'

docker_image("jpetazzo/nsenter") do
  action :pull
  retries 0
  retry_delay 2
  cookbook_name "app"
  recipe_name "nsenter"
  cmd_timeout 300
  image_name "jpetazzo/nsenter"
end



[2014-07-01T01:36:50+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-07-01T01:36:50+00:00] ERROR: Running exception handlers
[2014-07-01T01:36:50+00:00] ERROR: Exception handlers complete
[2014-07-01T01:36:50+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-07-01T01:36:50+00:00] ERROR: docker_image[jpetazzo/nsenter] (app::nsenter line 1) had an error: TypeError: no implicit conversion of nil into String
[2014-07-01T01:36:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

docker_container error:
```
================================================================================
Error executing action `run` on resource 'docker_container[jpetazzo/nsenter]'
================================================================================


TypeError
---------
no implicit conversion of nil into String


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:144:in `start_with?'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:144:in `container_id_matches?'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:126:in `container_matches?'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:7:in `block in load_current_resource'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:6:in `each'
/var/lib/aws/opsworks/cache/cookbooks/docker/providers/container.rb:6:in `load_current_resource'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache/cookbooks/app/recipes/nsenter.rb

  3: docker_container "jpetazzo/nsenter" do
  4:     volume "/usr/local/bin:/target"
  5: end


Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache/cookbooks/app/recipes/nsenter.rb:3:in `from_file'

docker_container("jpetazzo/nsenter") do
  action :run
  retries 0
  retry_delay 2
  cookbook_name "app"
  recipe_name "nsenter"
  volume "/usr/local/bin:/target"
  cmd_timeout 60
end



[2014-07-01T16:54:25+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-07-01T16:54:25+00:00] ERROR: Running exception handlers
[2014-07-01T16:54:25+00:00] ERROR: Exception handlers complete
[2014-07-01T16:54:25+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-07-01T16:54:25+00:00] ERROR: docker_container[jpetazzo/nsenter] (app::nsenter line 3) had an error: TypeError: no implicit conversion of nil into String
[2014-07-01T16:54:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by someara** [comment]
Closing due to age. These resources have been re-implemented in master
