### ISSUE TITLE
node['docker']['docker_daemon_timeout'] being ignored?

### ISSUE THREAD

**Issue by bplunkert** [bflad/chef-docker#186]
I am unable to consistently reproduce this issue, but in certain environments, it seems the docker_container's cmd_timeout parameter is being ignored. I set the node['docker']['docker_daemon_timeout'] attribute and cmd_timeout parameter to 1200 (which I believe should be 1200sec == 20min):
```
node.set['docker']['docker_daemon_timeout'] = 1200

docker_container 'redis-cache' do
  image 'dockerfile/redis'
  container_name 'redis-cache'
  detach true
  cmd_timeout 1200
  action :run
end
```

However, in my CI environment I see the failure usually occurring at around 10 mins, due to a timeout (output condensed for readability):
```
* docker_container[redis-cache] action run
[2014-07-04T00:56:44+00:00] INFO: Processing docker_container[redis-cache] action run (runnable_docker::registry line 28)

================================================================================       
Error executing action `run` on resource 'docker_container[redis-cache]'      
================================================================================       
Helpers::Docker::DockerNotReady       
-------------------------------       
docker timeout exceeded       
 

Cookbook Trace:       
---------------       
/tmp/kitchen/cookbooks/docker/libraries/helpers.rb:232:in `rescue in wait_until_ready!'       
/tmp/kitchen/cookbooks/docker/libraries/helpers.rb:223:in `wait_until_ready!'       
/tmp/kitchen/cookbooks/docker/providers/container.rb:5:in `load_current_resource'       


Resource Declaration:       
---------------------       
# In /tmp/kitchen/cookbooks/runnable_docker/recipes/registry.rb       

 28: docker_container 'redis-cache' do       
 29:   image 'dockerfile/redis'       
 30:   container_name 'redis-cache'       
 31:   detach true       
 32:   cmd_timeout 1200       
 33:   action :run       
 34: end       
 35:        


Compiled Resource:       
------------------       
# Declared in /tmp/kitchen/cookbooks/runnable_docker/recipes/registry.rb:28:in `from_file'       

docker_container("redis-cache") do       
  action [:run]       
  retries 0       
  retry_delay 2       
  guard_interpreter :default       
  cookbook_name :runnable_docker       
  recipe_name "registry"       
  image "dockerfile/redis"       
  container_name "redis-cache"       
  detach true
  cmd_timeout 1200
end

[2014-07-04T00:56:58+00:00] INFO: Running queued delayed notifications before re-raising exception
```

**Comment by someara** [comment]
Attributes API is being deprecated as of 0.40.x
