### ISSUE TITLE
package-lxc-ubuntu-1404 fails kitchen test with lxc-start error

### ISSUE THREAD

**Issue by bplunkert** [bflad/chef-docker#188]
```
[2014-07-07T20:17:03+00:00] INFO: Processing docker_image[docker_image_build_1] action build (docker_test::image_lwrp line 16)       
       
================================================================================       
Error executing action `build` on resource 'docker_image[docker_image_build_1]'       
================================================================================       
       
       
Mixlib::ShellOut::ShellCommandFailed       
------------------------------------       
Expected process to exit with [0], but received '1'       
---- Begin output of docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile ----       
STDOUT: Step 0 : FROM busybox       
        ---> a9eb17255234
       Step 1 : RUN /bin/echo 'hello from docker_image_build_1'
        ---> Running in daf716e55ca6
       lxc-start: symbol lookup error: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync
       
       STDERR: Sending build context to Docker daemon 2.048 kB
       Sending build context to Docker daemon 
       2014/07/07 20:17:03 The command [/bin/sh -c /bin/echo 'hello from docker_image_build_1'] returned a non-zero code: 127
       ---- End output of docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile ----
       Ran docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile returned 1
       
       
       Cookbook Trace:
       
       ---------------
       /tmp/kitchen/cache/cookbooks/docker/libraries/helpers.rb:272:in `execute_cmd!'
       /tmp/kitchen/cache/cookbooks/docker/libraries/helpers.rb:265:in `docker_cmd!'
       /tmp/kitchen/cache/cookbooks/docker/providers/image.rb:127:in `build'
       /tmp/kitchen/cache/cookbooks/docker/providers/image.rb:25:in `block in class_from_file'
       
       
       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/docker_test/recipes/image_lwrp.rb
       
        16: docker_image 'docker_image_build_1' do
        17:   tag 'docker_image_build_1_tag'
        18:   source docker_image_build_1_file
        19:   action [:build, :remove]
        20: end
        21: 
        22: docker_image_build_2_dir = '/tmp/docker_image_build_2'
        23: 
        24: directory docker_image_build_2_dir
        25: 
        26: file "#{docker_image_build_2_dir}/foo.txt" do
        27:   content 'Dockerfile_2 contains ADD for this file'
        28: end
        29: 
        30: cookbook_file "#{docker_image_build_2_dir}/Dockerfile" do
        31:   source 'Dockerfile_2'
        32: end
        33: 
        34: docker_image 'docker_image_build_2' do
        35:   source docker_image_build_2_dir
        36:   action :build
        37: end
       
       
       
       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/docker_test/recipes/image_lwrp.rb:16:in `from_file'
       
       docker_image("docker_image_build_1") do
         action [:build, :remove]
         retries 0
         retry_delay 2
         guard_interpreter :default
         cookbook_name "docker_test"
         recipe_name "image_lwrp"
         tag "docker_image_build_1_tag"
         source "/tmp/docker_image_build.dockerfile"
         cmd_timeout 300
         image_name "docker_image_build_1"
       end
       
       
       
[2014-07-07T20:17:03+00:00] INFO: Running queued delayed notifications before re-raising exception       
[2014-07-07T20:17:03+00:00] INFO: template[/etc/default/lxc] sending restart action to service[lxc-net] (delayed)       
Recipe: lxc::default       
  * service[lxc-net] action restart[2014-07-07T20:17:03+00:00] INFO: Processing service[lxc-net] action restart (lxc::default line 90)       
       [2014-07-07T20:17:03+00:00] INFO: service[lxc-net] restarted
       
           - restart service service[lxc-net]
       
       
       Running handlers:
       [2014-07-07T20:17:03+00:00] ERROR: Running exception handlers
       Running handlers complete
       
       [2014-07-07T20:17:03+00:00] ERROR: Exception handlers complete
       [2014-07-07T20:17:03+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 39 resources updated in 378.320975494 seconds
[2014-07-07T20:17:04+00:00] ERROR: docker_image[docker_image_build_1] (docker_test::image_lwrp line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'       
---- Begin output of docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile ----       
STDOUT: Step 0 : FROM busybox       
 ---> a9eb17255234       
Step 1 : RUN /bin/echo 'hello from docker_image_build_1'       
 ---> Running in daf716e55ca6       
lxc-start: symbol lookup error: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync       
       
       STDERR: Sending build context to Docker daemon 2.048 kB
       Sending build context to Docker daemon 
       2014/07/07 20:17:03 The command [/bin/sh -c /bin/echo 'hello from docker_image_build_1'] returned a non-zero code: 127
       ---- End output of docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile ----
       Ran docker build  --tag="docker_image_build_1:docker_image_build_1_tag" - < /tmp/docker_image_build.dockerfile returned 1
[2014-07-07T20:17:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)       
>>>>>> Converge failed on instance <package-lxc-ubuntu-1404>.
```

**Comment by john3exonets** [comment]
Any updates on this?  I'm getting similar errors:

$ lxs-create
No command 'lxs-create' found, did you mean:
 Command 'lxc-create' from package 'lxc' (main)
lxs-create: command not found
john@openstack1:~/.cloud-install$ lxc-create
lxc-create: symbol lookup error: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync
john@openstack1:~/.cloud-install$ lxc=ls
john@openstack1:~/.cloud-install$ lxc-ls
Traceback (most recent call last):
  File "/usr/bin/lxc-ls", line 31, in <module>
    import lxc
  File "/usr/lib/python3/dist-packages/lxc/__init__.py", line 26, in <module>
    import _lxc
ImportError: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync

This is on an Ubuntu 14.04 w/all updates as of today.

Thanks.

**Comment by someara** [comment]
Package installs deprecated as of 0.40.x
