### ISSUE TITLE
serverspec docker_container tests failing

### ISSUE THREAD

**Issue by bplunkert** [bflad/chef-docker#189]
I am seeing failures running kitchen test which appear to be related to the docker_container tests "be_running" and "be_a_container". I am including some examples here -- this appears to be occurring across all the "should" (not "should_not") specs [here](https://github.com/bflad/chef-docker/blob/master/test/shared/spec/container_spec.rb)

```
6) package-native behaves like a docker container test environment Docker container "busybox:latest running sleep 4444" should be a container       
     On host ``       
     Failure/Error: it { should be_a_container }       
              
       expected container? to return true, got false       
     Shared Example Group: "a docker container test environment" called from /tmp/busser/suites/serverspec/default_spec.rb:5       
     # /tmp/kitchen/data/spec/container_spec.rb:18:in `block (3 levels) in <top (required)>'       
       
7) package-native behaves like a docker container test environment Docker container "busybox:latest running sleep 4444" should be running       
     On host ``       
     Failure/Error: it { should be_running }       
              
       expected Docker container "busybox:latest running sleep 4444" to be running       
     Shared Example Group: "a docker container test environment" called from /tmp/busser/suites/serverspec/default_spec.rb:5       
     # /tmp/kitchen/data/spec/container_spec.rb:19:in `block (3 levels) in <top (required)>'       
       
```

The output of `docker ps` shows the sleep 4444 container running:
```
root@package-native-ubuntu-1204:~# docker ps | grep "sleep 4444"
5e90ceca7afd        busybox:buildroot-2014.02     sleep 4444             About an hour ago   Up About an hour                             insane_mccarthy     
```

**Comment by someara** [comment]
This should be fixed up as of 0.40.x
