### ISSUE TITLE
docker_container run: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by kpettijohn** [bflad/chef-docker#229]
My initial first run works as expected but the next time chef-client runs I get the following error. 

`no implicit conversion of nil into String`

Any feedback on how I can resolve this would be much appreciated and I apologize if I'm doing something obviously wrong! 

Here is the full output:

```
    ================================================================================
    Error executing action `run` on resource 'docker_container[registry]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:144:in `start_with?'
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:144:in `container_id_matches?'
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:126:in `container_matches?'
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:7:in `block in load_current_resource'
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:6:in `each'
    /root/.chef/local-mode-cache/cache/cookbooks/docker/providers/container.rb:6:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /root/.chef/local-mode-cache/cache/cookbooks/docker-registry/recipes/default.rb

     20: docker_container 'registry' do
     21:   image 'registry'
     22:   detach true
     23:   port node['docker-registry']['port']
     24:   env "SETTINGS_FLAVOR=#{node['docker-registry']['settings_flavor']}"
     25:   env "DOCKER_REGISTRY_CONFIG=#{node['docker-registry']['config_container_path']}/config.yml"
     26:   volume "#{node['docker-registry']['config_host_path']}:#{node['docker-registry']['config_container_path']}"
     27: end

    Compiled Resource:
    ------------------
    # Declared in /root/.chef/local-mode-cache/cache/cookbooks/docker-registry/recipes/default.rb:20:in `from_file'

    docker_container("registry") do
      action :run
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "docker-registry"
      recipe_name "default"
      image "registry"
      detach true
      port "5000:5000"
      env "DOCKER_REGISTRY_CONFIG=/registry-conf/config.yml"
      volume "/docker/registry:/registry-conf"
      cmd_timeout 60
    end


Running handlers:
[2014-11-06T17:43:38+00:00] ERROR: Running exception handlers
Running handlers complete
[2014-11-06T17:43:38+00:00] ERROR: Exception handlers complete
[2014-11-06T17:43:38+00:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 25.679801522 seconds
[2014-11-06T17:43:38+00:00] ERROR: docker_container[registry] (docker-registry::default line 20) had an error: TypeError: no implicit conversion of nil into String
[2014-11-06T17:43:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Here is the output from `docker ps -a --no-trunc`:

```
CONTAINER ID                                                       IMAGE               COMMAND                               CREATED             STATUS              PORTS                    NAMES
9126fafcd0359071cff5ba55bcad01594b006548fc9d4218c0b062e1096a6d58   registry:latest     "/bin/sh -c 'exec docker-registry'"   6 minutes ago       Up 6 minutes        0.0.0.0:5000->5000/tcp   registry
```

```
docker --version
Docker version 1.3.1, build 4e9bbfa
```

**Comment by mincedmit** [comment]
Just verified that this no longer happens to me on 0.36.0 FYI

**Comment by kpettijohn** [comment]
Sorry for the delay but I can also verify that this is no longer happening to me on `0.36.0`
