### ISSUE TITLE
Add attribute for cwd for docker_image

### ISSUE THREAD

**Issue by gionn** [bflad/chef-docker#291]
Imagine an use case like this:

```
git "#{Chef::Config[:file_cache_path]}/node-app" do
  repository 'https://gist.github.com/3b8ae2fd16f46acadea9.git'
  revision 'master'
  action :sync
end

docker_image "node-app" do
  tag "latest"
  source "#{Chef::Config[:file_cache_path]}/node-app/Dockerfile"
  action :build
end
```

Dockerfiles contains:

```
ADD app.js /var/www/app.js
```

fails with:

```
==> default: Step 12 : ADD app.js /var/www/app.js
==> default: STDERR: time="2015-04-03T22:24:13Z" level="info" msg="app.js: no such file or directory"
==> default: ---- End output of docker build  --tag="node-app:latest" - < /var/chef/cache/node-app/Dockerfile ----
==> default: Ran docker build  --tag="node-app:latest" - < /var/chef/cache/node-app/Dockerfile returned 1
==> default: [2015-04-03T22:24:13+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by senorsmile** [comment]
I just ran into this same bug.  Eventually determined that it is due to the way docker build is being called: 

```==> default: Ran docker build  --tag="node-app:latest" - < /var/chef/cache/node-app/Dockerfile returned 1```

is using stdin instead of a Dockerfile, which disables ADD, as documented here:
https://github.com/docker/docker/issues/841
and here
https://github.com/docker/docker/pull/845
.

**Comment by bflad** [comment]
Would it seem reasonable to cd to the directory and call `docker build .`? Will take a deeper look at this after 0.37.0 release.

**Comment by gionn** [comment]
Yes, this is the common workflow for building an image.

**Comment by senorsmile** [comment]
There is a native way to build containers using the chef lwrp, however it
currently has a bug.  This is a temporary workaround to just get things
working.

**Comment by senorsmile** [comment]
Disregard that last message... Thought this was my private repo.

**Comment by Soulou** [comment]
ping ? It's an annoying issue, it's impossible to build an image with a context (using `ADD`) with the cookbook as it is now. If it is, what's the  good way to achieve this?

**Comment by someara** [comment]
This is docker_image has been reimplemented in master and will be in the 1.0.0 release

**Comment by nozpheratu** [comment]
Is this still an issue for anybody else? Running v2.11.1 and it seems COPY isn't locating a file in the same directory as the Dockerfile specified in the `source` property.

```
├── files
│   └── default
│       ├── db
│       │   ├── create-user.sql
│       │   └── Dockerfile
├── metadata.rb
├── recipes
│   └── default.rb
```
**default.rb**
```ruby
directory "#{Chef::Config[:file_cache_path]}/docker/db" do
  owner 'root'
  recursive true
end

cookbook_file "db_dockerfile" do
  source "db/Dockerfile"
  path "#{Chef::Config[:file_cache_path]}/docker/db/Dockerfile"
  group "root"
  owner "root"
  mode 0440
end

cookbook_file "create_user_sql" do
  source "db/create-user.sql"
  path "#{Chef::Config[:file_cache_path]}/docker/db/create-user.sql"
  group "root"
  owner "root"
  mode 0440
end

docker_service 'default' do
  action [:create, :start]
end

docker_image 'db' do
  source "#{Chef::Config[:file_cache_path]}/docker/db/Dockerfile"
  action :build
end
```

**Dockerfile**
```docker
FROM mariadb

COPY create-user.sql /schema/000-create-user.sql
```
And this yields the following stacktrace:
```ruby
       Compiling Cookbooks...
       Converging 5 resources
       Recipe: guacamole::default
         * directory[/tmp/kitchen/cache/docker/db] action create (up to date)
         * cookbook_file[db_dockerfile] action create (up to date)
         * cookbook_file[create_user_sql] action create (up to date)
         * docker_service[default] action create
           * docker_installation_script[default] action create
             * apt_package[curl] action install (up to date)
             * execute[install docker] action run (up to date)
       (up to date)
            (up to date)
         * docker_service[default] action start
           * docker_service_manager_systemd[default] action start
             * directory[/usr/lib/docker] action create (up to date)
             * template[/usr/lib/docker/docker-wait-ready] action create (up to date)
             * template[/lib/systemd/system/docker.service] action create (up to date)
             * template[/lib/systemd/system/docker.socket] action create (up to date)
             * template[/etc/systemd/system/docker.service] action create (up to date)
             * template[/etc/systemd/system/docker.socket] action create (up to date)
             * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
             * service[docker] action enable (up to date)
             * service[docker] action start (up to date)
       (up to date)
            (up to date)
         * docker_image[db] action build

           ================================================================================
           Error executing action `build` on resource 'docker_image[db]'
           ================================================================================

           Docker::Error::UnexpectedResponseError
           --------------------------------------
           Couldn't find id: {"stream":"Step 1 : FROM mariadb\n"}
           {"stream":" ---\u003e 05a32751fb4d\n"}
           {"stream":"Step 2 : COPY create-user.sql /schema/000-create-user.sql\n"}
           {"errorDetail":{"message":"lstat create-user.sql: no such file or directory"},"error":"lstat create-user.sql: no such file or directory"}

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_image.rb:21:in `build_from_dockerfile'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_image.rb:50:in `build_image'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_image.rb:42:in `block (2 levels) in <class:DockerImage>'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_image.rb:41:in `block in <class:DockerImage>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/guacamole/recipes/default.rb

            32: docker_image 'db' do
            33:   source "#{Chef::Config[:file_cache_path]}/docker/db/Dockerfile"
            34:   action :build
            35: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/guacamole/recipes/default.rb:32:in `from_file'

           docker_image("db") do
             action [:build]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_image
             cookbook_name "guacamole"
             recipe_name "default"
             source "/tmp/kitchen/cache/docker/db/Dockerfile"
             repo "db"
             tag "latest"
             rm true
             connection #<Docker::Connection:0x00000004318db0 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
           end


       Running handlers:
       [2016-12-06T18:11:17+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-12-06T18:11:17+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 03 seconds
       [2016-12-06T18:11:17+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-12-06T18:11:17+00:00] ERROR: docker_image[db] (guacamole::default line 32) had an error: Docker::Error::UnexpectedResponseError: Couldn't find id: {"stream":"Step 1 : FROM mariadb\n"}
       {"stream":" ---\u003e 05a32751fb4d\n"}
       {"stream":"Step 2 : COPY create-user.sql /schema/000-create-user.sql\n"}
       {"errorDetail":{"message":"lstat create-user.sql: no such file or directory"},"error":"lstat create-user.sql: no such file or directory"}

       [2016-12-06T18:11:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-xenial64>.  Please see .kitchen/logs/default-ubuntu-xenial64.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by nozpheratu** [comment]
As a temporary workaround, compressing my `COPY` file and `Dockerfile` into a tar archive and building from that seems to work.

**Comment by olkgrab** [comment]
Confirm, have the same issue.

**Comment by Arqu07** [comment]
If you have a directory e.g `/path/dir/Dockerfile` and under it have some files which you want to copy using Dockerfile `COPY file /dst_path` and you get an error `no such file or directory` when your chef recipe looks like:
`docker_image 'some_name' do` 
   `source "/path/Dockerfile"`
   `action :build`
`end`
You should change your source path to 'source "/path/" without pointing the Dockerfile, you tell the recipe that under that are Dockerfile and other needed files.
