### ISSUE TITLE
No resource or method named `shell_out' for `Chef::Provider::DockerContainer ""'

### ISSUE THREAD

**Issue by jhmartin** [bflad/chef-docker#353]
Chef-client 11.18.12 using chef-server 11.8:
```
    ================================================================================
    Error executing action `run` on resource 'docker_container[registry]'
    ================================================================================

    NoMethodError
    -------------
    No resource or method named `shell_out' for `Chef::Provider::DockerContainer ""'

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/libraries/helpers.rb:201:in `block (2 levels) in wait_until_ready!'
    /var/chef/cache/cookbooks/docker/libraries/helpers.rb:200:in `loop'
    /var/chef/cache/cookbooks/docker/libraries/helpers.rb:200:in `block in wait_until_ready!'
    /var/chef/cache/cookbooks/docker/libraries/helpers.rb:199:in `wait_until_ready!'
    /var/chef/cache/cookbooks/docker/providers/container.rb:5:in `load_current_resource'
```

**Comment by jhmartin** [comment]
As mentioned in https://www.chef.io/blog/2014/03/12/writing-libraries-in-chef-cookbooks/, the module needs to add 
```
    include Chef::Mixin::ShellOut
```

**Comment by alecxvs** [comment]
Linking the pull request: https://github.com/bflad/chef-docker/pull/354
Without this fix, the cookbook can't run on any Chef version < 12

**Comment by someara** [comment]
Closing this, as master now talks directly to the API instead of shelling out

**Comment by someara** [comment]
Chef 11 is not supported by this cookbook.
Please upgrade to Chef 12.
