### ISSUE TITLE
Error: cannot mount volume over existing file, file exists

### ISSUE THREAD

**Issue by rudijs** [bflad/chef-docker#384]
Hi,

Using cookbook version 1.0.6 and Docker version 1.7.1, build 786b29d.

I'm able to:

    sudo docker run -v /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

But the same in a recipe throws:

    cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/775ab3bbf662c0b29ae5e582ccc96b24c48378ce4ced2fd948f52dfdea765365/etc/prometheus/prometheus.yml

```
docker_container "rsm-prometheus" do
  repo "prom/prometheus"
  volumes [
              "/home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml"
          ]
end
```

The prometheus [docker](https://github.com/prometheus/prometheus/blob/master/Dockerfile#L11) file does create the prometheus.yml file.

Command line can "mount over it" but the cookbook throws.

It was working pre v1.0.0 but since upgrading it throws.

Am I doing something wrong here?

Thanks.

Full Error:

```
Recipe: docker-prometheus::prometheus
  * docker_image[prom/prometheus] action pull_if_missing (up to date)
  * template[/home/ubuntu/prometheus.yml] action create (up to date)
  * docker_container[rsm-prometheus] action run_if_missing
    
    ================================================================================
    Error executing action `run_if_missing` on resource 'docker_container[rsm-prometheus]'
    ================================================================================
    
    Docker::Error::ServerError
    --------------------------
    cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/b6c324476bb061ec9bf0146b6c5bc2575f2f487aead4df307e545f6de090cb3c/etc/prometheus/prometheus.ym
l
    
    Cookbook Trace:
    ---------------
    /home/vagrant/chef-solo/cookbooks-2/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:50:in `rescue in request'
    /home/vagrant/chef-solo/cookbooks-2/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:38:in `request'
    /home/vagrant/chef-solo/cookbooks-2/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
    /home/vagrant/chef-solo/cookbooks-2/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/container.rb:231:in `create'
    /home/vagrant/chef-solo/cookbooks-2/docker/libraries/provider_docker_container.rb:132:in `create_container'
    /home/vagrant/chef-solo/cookbooks-2/docker/libraries/provider_docker_container.rb:191:in `block (2 levels) in <class:DockerContainer>'
    /home/vagrant/chef-solo/cookbooks-2/docker/libraries/provider_docker_container.rb:190:in `block in <class:DockerContainer>'
    /home/vagrant/chef-solo/cookbooks-2/docker/libraries/provider_docker_container.rb:256:in `block in <class:DockerContainer>'
    /home/vagrant/chef-solo/cookbooks-2/docker/libraries/provider_docker_container.rb:263:in `block in <class:DockerContainer>'
    
    Resource Declaration:
    ---------------------
    # In /home/vagrant/chef-solo/cookbooks-3/docker-prometheus/recipes/prometheus.rb
    
     12: docker_container "rsm-prometheus" do
     13:   repo "prom/prometheus"
     14:   volumes [
     15:               "/home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml"
     16:           ]
     17: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/vagrant/chef-solo/cookbooks-3/docker-prometheus/recipes/prometheus.rb:12:in `from_file'
    
    docker_container("rsm-prometheus") do
      action :run_if_missing
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_container
      cookbook_name :"docker-prometheus"
      recipe_name "prometheus"
      repo "prom/prometheus"
      restart_policy "no"
      volumes ["/home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml"]
      restart_maximum_retry_count 0
      container_name "rsm-prometheus"
      tag "latest"
      attach_stderr true
      attach_stdout true
      memory 0
      memory_swap 0
    end
    

Running handlers:
[2015-08-21T05:37:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-21T05:37:16+00:00] ERROR: Exception handlers complete
[2015-08-21T05:37:16+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 3 resources updated in 2.347715066 seconds
[2015-08-21T05:37:16+00:00] ERROR: docker_container[rsm-prometheus] (docker-prometheus::prometheus line 12) had an error: Docker::Error::ServerError: cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/b6c324476bb061ec9bf0146b6c5bc2575f2f487aead4df307e545f6de090cb3c/etc/prometheus/prometheus.yml

[2015-08-21T05:37:16+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by rudijs** [comment]
Ah .. adding a ro (or rw) to the volume fixes it for me.

```
  volumes [
              "/home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
          ]
```

**Comment by someara** [comment]
Also, check out the "binds" property

https://github.com/bflad/chef-docker/blob/master/test/cookbooks/docker_test/recipes/container.rb#L240

**Comment by rudijs** [comment]
@someara 

Hi, Yeah I was looking at "binds" when the ":ro" suffix worked out for me.

In another recipe I had a similar problem and the ":ro" suffix is not working out.

Using binds does the trick.

```
  binds [
             "/opt/grafana:/var/lib/grafana",
             "/opt/grafana-plugins/datasources/prometheus:/usr/share/grafana/public/app/plugins/datasource/prometheus"
         ]
```

I'm still googling around to find more info so it's clear in my head which to use when.

**Comment by rudijs** [comment]
Which to use when .. I mean when to use binds and when to use volume.

**Comment by rudijs** [comment]
OK I think I got it.

volumes for exposed paths
binds for things I want to add "manually".

For Grafana a combo like this works:

```
  volumes [
            "/opt/grafana:/var/lib/grafana"
        ]
  binds [
             "/opt/grafana-plugins/datasources/prometheus:/usr/share/grafana/public/app/plugins/datasource/prometheus"
         ]
```

**Comment by someara** [comment]
Post 1.0.0 "volumes" now works like the VOLUME directive in a Dockerfile.

... which is actually a different from the language used by the Docker CLI
(dash v for volumes actually means "binds")

For the most part, the docker_container properties should align with the
json keys in the Docker Remote API.

The best source truth are the docs found here:

https://docs.docker.com/reference/api/docker_remote_api/
