### ISSUE TITLE
no images from default registry after login

### ISSUE THREAD

**Issue by poelzi** [bflad/chef-docker#397]
after a login with credentials for a specific private registry, it is no longer possible to use images from the official one.

```
docker_registry 'https://registry.corp.example' do
    username 'deployer'
    password 'deployme'
    email 'deployer@corp.example'
end

docker_image 'cirros' do
  action :pull
end
```

This fails. docker log:

```
INFO[339444] GET /v1.16/images/logstash:latest/json
ERRO[339444] Handler for GET /images/{name:.*}/json returned error: No such image: logstash:latest
ERRO[339444] HTTP Error                                    err=No such image: logstash:latest statusCode=404
```

chef debug log
```
       [2015-08-25T16:41:32+00:00] DEBUG: Provider for action pull on resource docker_image[logstash] is Chef::Provider::DockerImage
       [2015-08-25T16:41:32+00:00] DEBUG: [:get, "/v1.16/images/logstash:latest/json", {}, nil]
       [2015-08-25T16:41:32+00:00] DEBUG: [:post, "/v1.16/images/create", {"fromImage"=>"logstash", "tag"=>"latest"}, nil]
       
           
           ================================================================================
           Error executing action `pull` on resource 'docker_image[logstash]'
           ================================================================================
           
           Docker::Error::TimeoutError
           ---------------------------
           read timeout reached
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:52:in `rescue in request'
           /tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:38:in `request'
           /tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
           /tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.2/lib/docker/image.rb:109:in `create'
           /tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_image.rb:67:in `pull_image'
           /tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_image.rb:126:in `block in <class:DockerImage>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/xxx-logging/recipes/logstash.rb
           
            62: docker_image 'logstash'
            63: #
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/xxx-logging/recipes/logstash.rb:62:in `from_file'
           
           docker_image("logstash") do
             action [:pull]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_image
             cookbook_name "xxx-logging"
             recipe_name "logstash"
             repo "logstash"
             tag "latest"
             api_retries 3
           end
           
```

it seems like the auth information is used, even when the server repository string does not match the repository it is pulled from.

**Comment by someara** [comment]
Dupe with #379
