### ISSUE TITLE
undefined method `working_dir' for LWRP resource docker_container from cookbook docker

### ISSUE THREAD

**Issue by KostyaSha** [bflad/chef-docker#475]
```
 ================================================================================
 Error executing action `run_if_missing` on resource 'docker_container[zookeeper]'
 ================================================================================
 NoMethodError
 -------------
 undefined method `working_dir' for LWRP resource docker_container from cookbook docker
 Cookbook Trace:
 ---------------
 /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:175:in `block in <class:DockerContainer>'
 /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:264:in `block in <class:DockerContainer>'
 /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:271:in `block in <class:DockerContainer>'
 Resource Declaration:
 ---------------------
 # In /var/chef/cache/cookbooks/cookbook/recipes/zookeeper.rb

  31: docker_container "zookeeper" do
  32: #  name "zookeeper"
  33:   repo zoo_image
  34:   tag node['TAG']
  35:   binds ["#{data_dir}:/home/app/data"]
  36:   port "2181:2181"
  37:   restart_policy 'always'
  38: end
  39:

 Compiled Resource:
 ------------------
 # Declared in /var/chef/cache/cookbooks/cookbook/recipes/zookeeper.rb:31:in `from_file'

 docker_container("image") do
   action [:run_if_missing]
   retries 0
   retry_delay 2
   default_guard_interpreter :default
   declared_type :docker_container
   cookbook_name "perf-env"
   recipe_name "zookeeper"
   repo "repo:5000/var-zookeeper"
   tag "latest"
   binds ["/srv/docker/image/data:/home/app/data"]
   port "2181:2181"
   restart_policy "always"
   container_name "image"
 end
```
Any idea?

**Comment by KostyaSha** [comment]
Seems caused by bad parameter...

**Comment by chasebolt** [comment]
Can you elaborate on what parameter caused the issue?

**Comment by KostyaSha** [comment]
I copied generated block and removed additional attributes and it works. Sounds like comment, but i not sure...
